import { defineConfig, globalIgnores } from "eslint/config";
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import pluginRouter from "@tanstack/eslint-plugin-router";
import pluginQuery from "@tanstack/eslint-plugin-query";
import prettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  globalIgnores([
    "dist/**",
    ".vite/**",
    ".tanstack/**",
    "build/**",
    // Generated by the router plugin; linting it is pure noise.
    "src/routeTree.gen.ts",
    // Leftovers from before the TanStack Start migration. Nothing produces
    // these any more, but any checkout that once ran `next build` still has
    // them — including the self-hosted CI runner, which checks out with
    // `clean: false`. Without this, eslint walks into .next/ and either lints
    // build output or crashes on a file that vanished mid-run.
    ".next/**",
    "next-env.d.ts",
  ]),
  js.configs.recommended,
  ...tseslint.configs.recommended,
  reactHooks.configs.flat.recommended,
  // `create-route-property-order` enforces validateSearch -> loaderDeps ->
  // beforeLoad -> loader, an ordering this migration depends on.
  ...pluginRouter.configs["flat/recommended"],
  // `exhaustive-deps` catches query keys that omit a filter.
  ...pluginQuery.configs["flat/recommended"],
  prettier,
]);

export default eslintConfig;
