/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardLinksRouteImport } from './routes/dashboard/links'
import { Route as DashboardManageRouteRouteImport } from './routes/dashboard/manage/route'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard/transactions'
import { Route as PCodeRouteImport } from './routes/p/$code'
import { Route as DashboardManageIndexRouteImport } from './routes/dashboard/manage/index'
import { Route as DashboardManageCategoriesRouteImport } from './routes/dashboard/manage/categories'
import { Route as DashboardManageLinksRouteImport } from './routes/dashboard/manage/links'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageRouteRoute = DashboardManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManageIndexRoute = DashboardManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardManageRouteRoute,
} as any)
const DashboardManageCategoriesRoute =
  DashboardManageCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardManageRouteRoute,
  } as any)
const DashboardManageLinksRoute = DashboardManageLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardManageRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/manage': typeof DashboardManageRouteRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/p/$code': typeof PCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/manage/categories': typeof DashboardManageCategoriesRoute
  '/dashboard/manage/links': typeof DashboardManageLinksRoute
  '/dashboard/manage/': typeof DashboardManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/p/$code': typeof PCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/manage/categories': typeof DashboardManageCategoriesRoute
  '/dashboard/manage/links': typeof DashboardManageLinksRoute
  '/dashboard/manage': typeof DashboardManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/manage': typeof DashboardManageRouteRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/p/$code': typeof PCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/manage/categories': typeof DashboardManageCategoriesRoute
  '/dashboard/manage/links': typeof DashboardManageLinksRoute
  '/dashboard/manage/': typeof DashboardManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/manage'
    | '/dashboard/categories'
    | '/dashboard/links'
    | '/dashboard/transactions'
    | '/p/$code'
    | '/dashboard/'
    | '/dashboard/manage/categories'
    | '/dashboard/manage/links'
    | '/dashboard/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/categories'
    | '/dashboard/links'
    | '/dashboard/transactions'
    | '/p/$code'
    | '/dashboard'
    | '/dashboard/manage/categories'
    | '/dashboard/manage/links'
    | '/dashboard/manage'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/manage'
    | '/dashboard/categories'
    | '/dashboard/links'
    | '/dashboard/transactions'
    | '/p/$code'
    | '/dashboard/'
    | '/dashboard/manage/categories'
    | '/dashboard/manage/links'
    | '/dashboard/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PCodeRoute: typeof PCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/links': {
      id: '/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage': {
      id: '/dashboard/manage'
      path: '/manage'
      fullPath: '/dashboard/manage'
      preLoaderRoute: typeof DashboardManageRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manage/': {
      id: '/dashboard/manage/'
      path: '/'
      fullPath: '/dashboard/manage/'
      preLoaderRoute: typeof DashboardManageIndexRouteImport
      parentRoute: typeof DashboardManageRouteRoute
    }
    '/dashboard/manage/categories': {
      id: '/dashboard/manage/categories'
      path: '/categories'
      fullPath: '/dashboard/manage/categories'
      preLoaderRoute: typeof DashboardManageCategoriesRouteImport
      parentRoute: typeof DashboardManageRouteRoute
    }
    '/dashboard/manage/links': {
      id: '/dashboard/manage/links'
      path: '/links'
      fullPath: '/dashboard/manage/links'
      preLoaderRoute: typeof DashboardManageLinksRouteImport
      parentRoute: typeof DashboardManageRouteRoute
    }
  }
}

interface DashboardManageRouteRouteChildren {
  DashboardManageCategoriesRoute: typeof DashboardManageCategoriesRoute
  DashboardManageLinksRoute: typeof DashboardManageLinksRoute
  DashboardManageIndexRoute: typeof DashboardManageIndexRoute
}

const DashboardManageRouteRouteChildren: DashboardManageRouteRouteChildren = {
  DashboardManageCategoriesRoute: DashboardManageCategoriesRoute,
  DashboardManageLinksRoute: DashboardManageLinksRoute,
  DashboardManageIndexRoute: DashboardManageIndexRoute,
}

const DashboardManageRouteRouteWithChildren =
  DashboardManageRouteRoute._addFileChildren(DashboardManageRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardManageRouteRoute: typeof DashboardManageRouteRouteWithChildren
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardManageRouteRoute: DashboardManageRouteRouteWithChildren,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PCodeRoute: PCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
